ALTER TABLE posts ADD COLUMN heart_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN plus_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN minus_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN laugh_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN love_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN cry_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN shock_count INT DEFAULT 0 NOT NULL;
ALTER TABLE posts ADD COLUMN angry_count INT DEFAULT 0 NOT NULL;
